add_test( [==[operator== returns true for equal states]==] [==[/workspaces/puzzle mp/test]==] [==[operator== returns true for equal states]==]  )
set_tests_properties( [==[operator== returns true for equal states]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[operator== returns false for unequal states]==] [==[/workspaces/puzzle mp/test]==] [==[operator== returns false for unequal states]==]  )
set_tests_properties( [==[operator== returns false for unequal states]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[operator< enforces proper ordering]==] [==[/workspaces/puzzle mp/test]==] [==[operator< enforces proper ordering]==]  )
set_tests_properties( [==[operator< enforces proper ordering]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[Default constructor returns solved puzzle]==] [==[/workspaces/puzzle mp/test]==] [==[Default constructor returns solved puzzle]==]  )
set_tests_properties( [==[Default constructor returns solved puzzle]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[getNeighbors returns correct neighbors]==] [==[/workspaces/puzzle mp/test]==] [==[getNeighbors returns correct neighbors]==]  )
set_tests_properties( [==[getNeighbors returns correct neighbors]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[getNeighbors edge cases]==] [==[/workspaces/puzzle mp/test]==] [==[getNeighbors edge cases]==]  )
set_tests_properties( [==[getNeighbors edge cases]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[Simple manhattanDistance tests]==] [==[/workspaces/puzzle mp/test]==] [==[Simple manhattanDistance tests]==]  )
set_tests_properties( [==[Simple manhattanDistance tests]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[manhattanDistance using getNeighbor]==] [==[/workspaces/puzzle mp/test]==] [==[manhattanDistance using getNeighbor]==]  )
set_tests_properties( [==[manhattanDistance using getNeighbor]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[Complicated manhattanDistance tests]==] [==[/workspaces/puzzle mp/test]==] [==[Complicated manhattanDistance tests]==]  )
set_tests_properties( [==[Complicated manhattanDistance tests]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[BFS: Solve on solved puzzle]==] [==[/workspaces/puzzle mp/test]==] [==[BFS: Solve on solved puzzle]==]  )
set_tests_properties( [==[BFS: Solve on solved puzzle]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[BFS: Easy solve]==] [==[/workspaces/puzzle mp/test]==] [==[BFS: Easy solve]==]  )
set_tests_properties( [==[BFS: Easy solve]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[BFS: Spiral test]==] [==[/workspaces/puzzle mp/test]==] [==[BFS: Spiral test]==]  )
set_tests_properties( [==[BFS: Spiral test]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[BFS: Correct number of iterations]==] [==[/workspaces/puzzle mp/test]==] [==[BFS: Correct number of iterations]==]  )
set_tests_properties( [==[BFS: Correct number of iterations]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[A*: Solve on solved puzzle]==] [==[/workspaces/puzzle mp/test]==] [==[A*: Solve on solved puzzle]==]  )
set_tests_properties( [==[A*: Solve on solved puzzle]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[A*: Easy solve]==] [==[/workspaces/puzzle mp/test]==] [==[A*: Easy solve]==]  )
set_tests_properties( [==[A*: Easy solve]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[A*: Spiral test]==] [==[/workspaces/puzzle mp/test]==] [==[A*: Spiral test]==]  )
set_tests_properties( [==[A*: Spiral test]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[A*: Correct number of iterations]==] [==[/workspaces/puzzle mp/test]==] [==[A*: Correct number of iterations]==]  )
set_tests_properties( [==[A*: Correct number of iterations]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[A* much faster than BFS]==] [==[/workspaces/puzzle mp/test]==] [==[A* much faster than BFS]==]  )
set_tests_properties( [==[A* much faster than BFS]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
add_test( [==[My Test Case]==] [==[/workspaces/puzzle mp/test]==] [==[My Test Case]==]  )
set_tests_properties( [==[My Test Case]==] PROPERTIES WORKING_DIRECTORY [==[/workspaces/puzzle mp]==])
set( test_TESTS [==[operator== returns true for equal states]==] [==[operator== returns false for unequal states]==] [==[operator< enforces proper ordering]==] [==[Default constructor returns solved puzzle]==] [==[getNeighbors returns correct neighbors]==] [==[getNeighbors edge cases]==] [==[Simple manhattanDistance tests]==] [==[manhattanDistance using getNeighbor]==] [==[Complicated manhattanDistance tests]==] [==[BFS: Solve on solved puzzle]==] [==[BFS: Easy solve]==] [==[BFS: Spiral test]==] [==[BFS: Correct number of iterations]==] [==[A*: Solve on solved puzzle]==] [==[A*: Easy solve]==] [==[A*: Spiral test]==] [==[A*: Correct number of iterations]==] [==[A* much faster than BFS]==] [==[My Test Case]==])
